# Generated by Django 5.0.6 on 2024-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
